services:
  db_bolao_ada:
    image: postgres
    container_name: db_bolao_ada
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pg_bolao_ada:/var/lib/postgresql/data

  node_bolao_ada:
    container_name: node_bolao_ada
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_bolao_ada
    env_file:
      - .env

volumes:
  pg_bolao_ada: