services:
  db_bolao_ada:
    image: postgres
    container_name: db_bolao_ada
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env
    volumes:
      - pg_bolao_ada:/var/lib/postgresql/data

  node_bolao_ada:
    container_name: node_bolao_ada
    build: .
    ports:
      - 80:5000
    depends_on:
      - db_bolao_ada
    env_file:
      - .env

volumes:
  pg_bolao_ada: